services:
  postgres:
    image: postgres:16
    container_name: andesfin_postgres
    restart: always
    environment:
      POSTGRES_DB: andesfin_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - andesfin_network

  backend:
    build: .
    container_name: andesfin_backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/andesfin_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - andesfin_network

volumes:
  postgres_data:

networks:
  andesfin_network:
    driver: bridge